$schema: http://json-schema.org/draft-07/schema#
type: object
description: |
  This file is written Yaml (Yaml.org)

  Scalars can be specified as numbers or strings.
   - Numbers are always interpreted as metric ('mm', 'mm/min' or 'rpm')
   - Strings can have units and fractions:
       . Valid units for sizes are 'cm', 'mm', 'in', 'inch', 'mil' or 'thou'
       . Valid feedrate units are 'mm/min', 'mm/s', 'in/min' or 'ipm'
       - Example: 4um, 12.4mm 23/64in, 100in/min, 24000rpm, 12deg

properties:
  # Version of this schema
  schema_version:
    type: integer
    const: 1
    description: Schema/data format version for this file.

  units:
    description: Global preferred unit system and display units.
    type: string
    enum: [mm, mil, in]
    default: mm
  theme:
    description: Application theme.
    type: string
    enum: [Light, Dark]
    default: Light

  selected_process_profile_id:
    description: |
      ID of the currently selected process profile.
    type: [string, "null"]
    default: null

  selected_cnc_profile_id:
    description: |
      ID of the currently selected CNC profile.
    type: [string, "null"]
    default: null

  selected_fixture_profile_id:
    description: |
      ID of the currently selected fixture profile.
    type: [string, "null"]
    default: null

  selected_toolset_profile_id:
    description: |
      ID of the currently selected toolset profile.
    type: [string, "null"]
    default: null

required:
  [
    units,
    theme,
    selected_process_profile_id,
    selected_cnc_profile_id,
    selected_fixture_profile_id,
    selected_toolset_profile_id,
  ]
additionalProperties: false
